### ISSUE TITLE
[Warning] Use RbConfig instead of obsolete and deprecated Config.

### ISSUE THREAD

**Issue by mikaa123** [jimweirich/rake#8]
Ruby version 1.9.3
Warning when using Rake:
Use RbConfig instead of obsolete and deprecated Config

Hope this helps.

**Comment by drbrain** [comment]
Fixed!

**Comment by mikaa123** [comment]
Hi,
I'm still having that issue. My rake version is 0.8.7, and I've run
    gem update rake
    > Updating installed gems
    > Nothing to update

Am I doing something wrong?
Thank you

**Comment by drbrain** [comment]
The fix has not been released.  Please be patient.

**Comment by mikaa123** [comment]
Thanks, just wanted to make sure. :)
